---
- name: Run apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    pkg:
      - nginx
      - zsh
      - wget

- name: Start and enable Nginx if not started and not enabled
  service:
    name: nginx
    state: started
    enabled: yes
